### ISSUE TITLE
時刻表顯示排序

### ISSUE THREAD

**Issue by imjkg** [boggyjan/livetra#2]
目前順行逆行中，時刻表是按造車種排序的，
是否能按時間排序，較符合一般使用習慣。

**Comment by boggyjan** [comment]
疑，現在是照時間排序沒錯哩～

**Comment by imjkg** [comment]
> 疑，現在是照時間排序沒錯哩～

我看起來是先排序車種再排序時間耶

![image](https://user-images.githubusercontent.com/9414959/54338554-2ead4e00-466d-11e9-8d33-18c64c6e9380.png)

**Comment by boggyjan** [comment]
但我沒做這個功能啊（抖。
之前的確有過從PTX取資料發現順序亂七八糟的情況，所以後來就做了在資料取回來後，以時間重新排序的功能。如果你用別的裝置或換個車站還是會一樣嗎？
下圖是我看到的畫面
![螢幕快照 2019-03-14 下午9 09 21](https://user-images.githubusercontent.com/2985856/54359483-b6ab4c00-469d-11e9-9810-be3559980aac.png)

**Comment by imjkg** [comment]
換不同裝置測試後，發現只有電腦上Chrome有此狀況，
ios上瀏覽器、電腦上Firefox皆正常。

**Comment by boggyjan** [comment]
真的耶！我修好了，感謝你！！
結果問題的原因在於上次提到的我有自己sort一次資料（因為現在PTX給的資料好像都是先照車種排，再照時間排）sort function是要return 1, 0, -1，我return true跟 false，結果偏偏只有chrome無法，偏偏我又沒用chrome測orz，總之感謝啦！OK的話就關掉囉～
